### ISSUE TITLE
插件无法使用

### ISSUE THREAD

**Issue by timeance** [smyhw/KQ-WelcomeMessage#1]
mirai-native:`1.8.1`
插件版本:`1.0.1` 

在 mirai 里看插件是成功加载上了，但是 data 目录并没有插件的文件夹，mirai 根目录也没有配置文件。
尝试在根目录创建`WelcomeMessage.txt`但依旧不会发送欢迎信息

以下是 mirai 中的信息
```
 23:02:55 [INFO] [Command] 标识符：online.smyhw.KQ.WelcomeMessage
状态：已启用 已加载
Id：8
CQ API：9 CQ API（JSON）：9
名称：进群欢迎语
版本：1.0.0 版本号：1
描述：[单一功能]:进群自动发欢迎语
作者：smyhw
注册了 2 个事件
类型：103 描述：群成员增加事件处理 方法名：_eventSystem_GroupMemberIncrease
类型：1003 描述：应用已被启用 方法名：_eventEnable
注册了 0 个悬浮窗项目
注册了 0 个菜单入口
```

**Comment by smyhw** [comment]
emmmm,根据你的描述我似乎无法复现这个问题,可以提供更详细的日志嘛?

插件的确不会再data目录下创建文件夹

准确的来说，插件会在**执行目录**下创建配置文件，如果是跨目录启动的mirai，那么配置文件则不一定处于mirai根目录下
如果启动时，日志里出现如下的输出项目，则说明配置加载正常，这时，可能证明配置文件创建在了其他目录下
```
16:56:35 [INFO] [MiraiNative] [进群欢迎语 初始化] 配置项目{QQ=123456789;msg=欢迎进群！
```

**Comment by timeance** [comment]
啊这，重新检查了一下发现确实在`jre\bin`文件夹下生成了配置文件，而且正确的设置后能够使用...
